spring:
  profiles:
    active: dev
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: {{packageName}}.manage.entity

seal:
  arch:
    json:
      objectmapper:
        ignoreClass:
          - javax.servlet.ServletRequest
          - javax.servlet.ServletResponse
          - org.springframework.core.io.InputStreamSource